### PR TITLE
Add TransformerOptions - option to cache length in for-of

### LINKED ISSUE #1: Transform for-of/for-in to normal for
Option for transforming `for..of` / `for..in` when targetting ES6 and above.

----

Based on my investigation,  `for..of` / `for..in` loops are slower than the traditional `for` loops (see the result: https://github.com/aminya/TypeScript-optimization)

It is pretty funny that when I target ES5, TypeScript converts `for..of` to the traditional loops, which makes the code faster, but I cannot do this when I target anything above ES6. 

I noticed that there is `"downlevelIteration"` which does the opposite of what I want.

## Use Cases

It enhances the performance but allows us to write readable code.

## Examples

```typescript
// for - in
  let sum = 0
  for (const i in arr) {
    sum += arr[i]
  }

// for - of
  let sum = 0
  for (const a of arr) {
    sum += a
  }

// should both be transformed to:
// Traditional
  let sum = 0
  for (let i = 0, l = arr.length; i < l; ++i) {
    sum += arr[i]
  }

// or
  let sum = 0
  for (let i = 0, l = arr.length; i < l; ++i) {
    let a = arr[i]
    sum += a
  }
```

### LINKED ISSUE #5: How to pass option for caching the length?
I checked the code for this transformer, and I noticed there is a condition that accepts if it can cache the length.

https://github.com/sapphi-red/ts-transformer-for-of/blob/bcfb65c90f15dd8151b88b5247468ecc7bd2e615/createStatement.ts#L33

How can I pass this option using ttsc?

### PR DESCRIPTION
**Pull request by aminya**
This adds an option to opt in using cached length in for-of. The tests are included

Fixes #5 
Closes #1 

image

### CODE REVIEW

**Comment by aminya** [comment]
@sapphi-red Please check this out as well 😃

**Review by sapphi-red — APPROVED** [review]
LGTM. Thank you!

**Comment by aminya** [comment]
Let me add an example to the readme.

**Comment by sapphi-red** [comment]
oops.
Would you create another PR for that please? 🙇

**Comment by aminya** [comment]
@sapphi-red Thank you ❤️ Here it is https://github.com/sapphi-red/ts-transformer-for-of/pull/7

**Pull request merged**
